### ISSUE TITLE
Develop a lightweight system for tracking sources which have been tried

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/scrapers#255]
Per @josh-chamberlain:
> so we can reduce duplication of effort (every time we run the MuckRock or CKAN scraper, for example, we should avoid trying to submit those sources which we already collected the previous time)

**Comment by josh-chamberlain** [comment]
closing as covered by https://github.com/Police-Data-Accessibility-Project/data-source-identification/issues/109
