### ISSUE TITLE
Looking to contribute

### ISSUE THREAD

**Issue by yoban-anaboy** [Police-Data-Accessibility-Project/Scrapers#39]
Hi, I'd like to contribute. What's the most valuable thing I could be doing? I've written a lot of scrapers in my day but I could also try submitting FOIA requests for additional data. Just looking for some initial direction.

**Comment by zgoulson** [comment]
Hello! Thanks for popping in. If you have joined our Slack, do head over to our [#_volunteer-start](https://policeaccessibility.slack.com/archives/C01JCB7TTJN) channel. This [document](https://docs.google.com/document/d/1Wjvv0NT3eECATJ4r8GQwEgS-sPqYFW8IGC8jvn3Bu5o) is pinned there which should help answer some of your questions. If you still have questions, please feel free to ask them here or in the Slack channel!
